production:
  adapter: mysql
  encoding: utf8
  reconnect: false
  database: db_name
  pool: 5
  username: user
  password: pass
  host: 127.0.0.1
development:
  adapter: mysql
  encoding: utf8
  reconnect: yes
  database: db_name
  pool: 5
  username: user
  password: pass
  host: localhost
test:
  development



